"""three migration

Revision ID: 566bde085d8d
Revises: 3fc8f780cb02
Create Date: 2017-12-22 11:34:05.819000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566bde085d8d'
down_revision = '3fc8f780cb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
